# Generated by Django 4.2.29 on 2026-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_startupprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_power',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Water', 'Water'), ('Electric', 'Electric'), ('Wind', 'Wind'), ('Earth', 'Earth'), ('Wizard', 'Wizard'), ('Magic', 'Magic'), ('Shadow', 'Shadow'), ('Light', 'Light'), ('Tech', 'Tech'), ('Nature', 'Nature'), ('Ice', 'Ice'), ('Metal', 'Metal'), ('Toxic', 'Toxic'), ('Gravity', 'Gravity'), ('Time', 'Time'), ('Chaos', 'Chaos'), ('Order', 'Order'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Spiderman', 'Spiderman'), ('Batman', 'Batman'), ('Hulk', 'Hulk'), ('Thor', 'Thor'), ('Captain America', 'Captain America'), ('Doremon', 'Doremon')], default='Tech', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_seed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
