# Generated by Django 4.2.29 on 2026-04-21 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_report_drive_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reports.report')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Message',
                'verbose_name_plural': 'Report Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
