# Generated by Django 4.2.29 on 2026-04-04 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='reports/screenshots/')),
                ('status', models.CharField(choices=[('pending_admin_review', 'Pending Admin Review'), ('approved', 'Approved'), ('spam', 'Spam'), ('duplicate', 'Duplicate'), ('fixed', 'Fixed')], default='pending_admin_review', max_length=25)),
                ('admin_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
