# Generated by Django 4.2.29 on 2026-04-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='drive_link',
            field=models.URLField(blank=True, help_text='Google Drive link (must be open to anyone with the link)', max_length=500, null=True),
        ),
    ]
